In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [3]:
df=pd.read_csv('titanic_toy.csv')

In [4]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64
 3   Survived  891 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [6]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [7]:
x=df.iloc[:,0:3]

In [8]:
y=df.iloc[:,-1]

In [9]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [10]:
x

      Age     Fare  Family
0    22.0   7.2500       1
1    38.0  71.2833       1
2    26.0   7.9250       0
3    35.0  53.1000       1
4    35.0   8.0500       0
..    ...      ...     ...
886  27.0  13.0000       0
887  19.0  30.0000       0
888   NaN  23.4500       3
889  26.0      NaN       0
890  32.0   7.7500       0

[891 rows x 3 columns]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [12]:
x_train.shape,x_test.shape

((712, 3), (179, 3))

In [13]:
x_train.isnull().mean()

Age       0.207865
Fare      0.050562
Family    0.000000
dtype: float64

In [17]:
mean_age=x_train['Age'].mean()
median_age=x_train['Age'].median()
mean_fare=x_train['Fare'].mean()
median_fare=x_train['Fare'].median()

In [20]:
x_train['Age_median']=x_train['Age'].fillna(median_age)
x_train['Age_mean']=x_train['Age'].fillna(mean_age)
x_train['Fare_mean']=x_train['Fare'].fillna(mean_fare)
x_train['Fare_median']=x_train['Fare'].fillna(median_fare)

In [21]:
x_train.sample(6)

      Age      Fare  Family  Age_median   Age_mean  Fare_mean  Fare_median
856  45.0  164.8667       2       45.00  45.000000   164.8667     164.8667
5     NaN    8.4583       0       28.75  29.785904     8.4583       8.4583
850   4.0   31.2750       6        4.00   4.000000    31.2750      31.2750
246  25.0    7.7750       0       25.00  25.000000     7.7750       7.7750
87    NaN    8.0500       0       28.75  29.785904     8.0500       8.0500
255  29.0   15.2458       2       29.00  29.000000    15.2458      15.2458